### ISSUE TITLE
Warden: friendly fire - mp_friendlyfire

### ISSUE THREAD

**Issue by damian1231** [shanapu/MyJailbreak-CSS#10]
L 11/24/2017 - 17:47:16: [SM] Exception reported: Invalid convar handle 0 (error 4)

L 11/24/2017 - 17:47:16: [SM] Blaming: myjailbreak/warden.smx

L 11/24/2017 - 17:47:16: [SM] Call stack trace:

L 11/24/2017 - 17:47:16: [SM]   [0] ConVar.BoolValue.get

L 11/24/2017 - 17:47:16: [SM]   [1] Line 132, MyJailbreak/Modules/Warden/friendlyfire.sp::FriendlyFire_Event_RoundEnd

Dropped damian from server (Kicked from server)

func_physbox (soccerball) at (-3071.060 512.110 23.000) using obsolete or unknown material type.

Dropped Gilly from server (Kicked from server)

Server is hibernating

Game will not start until both teams have players.

Dropped Jason from server (Punting bot, server is hibernating)

Game will not start until both teams have players.

L 11/24/2017 - 17:47:21: [SM] Exception reported: Invalid convar handle 0 (error 4)

L 11/24/2017 - 17:47:21: [SM] Blaming: myjailbreak/warden.smx

L 11/24/2017 - 17:47:21: [SM] Call stack trace:

L 11/24/2017 - 17:47:21: [SM]   [0] ConVar.BoolValue.get

L 11/24/2017 - 17:47:21: [SM]   [1] Line 132, MyJailbreak/Modules/Warden/friendlyfire.sp::FriendlyFire_Event_RoundEnd

Dropped Greg from server (Punting bot, server is hibernating)

Game will not start until both teams have players.

Dropped Ian from server (Punting bot, server is hibernating)

func_physbox (soccerball) at (-3071.060 512.110 23.000) using obsolete or unknown material type.

Console: Cells will open automatically in 10 seconds!

CalcSequenceIndex: can't find 'idle_upper_knife'.

CalcSequenceIndex: can't find 'idle_upper_m4'.

CalcSequenceIndex: can't find 'walk_upper_knife'.

CalcSequenceIndex: can't find 'walk_upper_m4'.

CalcSequenceIndex: can't find 'crouch_idle_upper_m4'.

CalcSequenceIndex: can't find 'crouch_walk_upper_m4'.

CalcSequenceIndex: can't find 'idle_shoot_knife'.

CalcSequenceIndex: can't find 'run_upper_m4'.

CalcSequenceIndex: can't find 'run_upper_knife'.

CalcSequenceIndex: can't find 'run_shoot_knife'.

CalcSequenceIndex: can't find 'walk_shoot_knife'.

CalcSequenceIndex: can't find 'idle_shoot_m4'.

CalcSequenceIndex: can't find 'walk_shoot_m4'.

CalcSequenceIndex: can't find 'run_shoot_m4'.

CalcSequenceIndex: can't find 'idle_upper_pistol'.

CalcSequenceIndex: can't find 'walk_upper_pistol'.

CalcSequenceIndex: can't find 'reload_m4'.

CalcSequenceIndex: can't find 'walk_shoot_pistol'.

CalcSequenceIndex: can't find 'idle_shoot_pistol'.

CalcSequenceIndex: can't find 'run_upper_pistol'.

CalcSequenceIndex: can't find 'run_shoot_pistol'.

CalcSequenceIndex: can't find 'idle_shoot_gren1'.

CalcSequenceIndex: can't find 'idle_shoot_gren2'.

CalcSequenceIndex: can't find 'idle_upper_scout'.

CalcSequenceIndex: can't find 'walk_upper_scout'.

CalcSequenceIndex: can't find 'idle_shoot_scout'.

CalcSequenceIndex: can't find 'run_upper_scout'.

CalcSequenceIndex: can't find 'idle_upper_ak'.

CalcSequenceIndex: can't find 'walk_upper_ak'.

CalcSequenceIndex: can't find 'run_upper_ak'.

CalcSequenceIndex: can't find 'crouch_idle_upper_knife'.

CalcSequenceIndex: can't find 'crouch_walk_upper_knife'.

CalcSequenceIndex: can't find 'crouch_idle_upper_ak'.

CalcSequenceIndex: can't find 'crouch_walk_upper_ak'.

CalcSequenceIndex: can't find 'crouch_idle_upper_scout'.

CalcSequenceIndex: can't find 'crouch_walk_upper_scout'.

CalcSequenceIndex: can't find 'crouch_idle_shoot_scout'.

CalcSequenceIndex: can't find 'crouch_idle_upper_pistol'.

CalcSequenceIndex: can't find 'run_shoot_ak'.

CalcSequenceIndex: can't find 'crouch_idle_shoot_pistol'.

CalcSequenceIndex: can't find 'walk_shoot_ak'.

CalcSequenceIndex: can't find 'idle_shoot_ak'.

CalcSequenceIndex: can't find 'crouch_walk_upper_pistol'.

CalcSequenceIndex: can't find 'crouch_walk_shoot_pistol'.

L 11/24/2017 - 19:50:51: -------- Mapchange to jb_vipinthemix_v1_3 --------

Accelerator upload thread started.

Accelerator upload thread finished. (0 uploaded, 0 failed)

Accelerator upload thread terminated. (canceled = false)

L 11/24/2017 - 19:50:51: [GEOIP] GeoIP database info: GEO-106FREE 20171003 Build 1 Copyright (c) 2017 MaxMind Inc All Rights Reserved

L 11/24/2017 - 19:50:51: [SM] Exception reported: Fatal error creating dynamic native!

L 11/24/2017 - 19:50:51: [SM] Blaming: MyJailbreak/warden.smx

L 11/24/2017 - 19:50:51: [SM] Call stack trace:

L 11/24/2017 - 19:50:51: [SM]   [0] CreateNative

L 11/24/2017 - 19:50:51: [SM]   [1] Line 1358, MyJailbreak/warden.sp::AskPluginLoad2

L 11/24/2017 - 19:50:51: [SM] Failed to load plugin "MyJailbreak/warden.smx": unexpected error 23 in AskPluginLoad callback.

L 11/24/2017 - 19:50:51: [SM] Exception reported: Fatal error creating dynamic native!

L 11/24/2017 - 19:50:51: [SM] Blaming: MyJailbreak/weapons.smx

L 11/24/2017 - 19:50:51: [SM] Call stack trace:

L 11/24/2017 - 19:50:51: [SM]   [0] CreateNative

L 11/24/2017 - 19:50:51: [SM]   [1] Line 117, MyJailbreak/weapons.sp::AskPluginLoad2

L 11/24/2017 - 19:50:51: [SM] Failed to load plugin "MyJailbreak/weapons.smx": unexpected error 23 in AskPluginLoad callback.

L 11/24/2017 - 19:50:51: [SM] Exception reported: Fatal error creating dynamic native!

L 11/24/2017 - 19:50:51: [SM] Blaming: MyJailbreak/myjailbreak.smx

L 11/24/2017 - 19:50:51: [SM] Call stack trace:

L 11/24/2017 - 19:50:51: [SM]   [0] CreateNative

L 11/24/2017 - 19:50:51: [SM]   [1] Line 319, MyJailbreak/myjailbreak.sp::AskPluginLoad2

L 11/24/2017 - 19:50:51: [SM] Failed to load plugin "MyJailbreak/myjailbreak.smx": unexpected error 23 in AskPluginLoad callback.

L 11/24/2017 - 19:50:51: [SM] Exception reported: Fatal error creating dynamic native!

L 11/24/2017 - 19:50:51: [SM] Blaming: MyJailbreak/icons.smx

L 11/24/2017 - 19:50:51: [SM] Call stack trace:

L 11/24/2017 - 19:50:51: [SM]   [0] CreateNative

L 11/24/2017 - 19:50:51: [SM]   [1] Line 636, MyJailbreak/icons.sp::AskPluginLoad2

L 11/24/2017 - 19:50:51: [SM] Failed to load plugin "MyJailbreak/icons.smx": unexpected error 23 in AskPluginLoad callback.

ConVarRef room_type doesn't point to an existing ConVar

**Comment by shanapu** [comment]
you don't need to post the console output. 
Just post your error logs found in cstrike/addons/sourcemod/logs.

The only usefull part is this:
```
L 11/24/2017 - 17:47:16: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 11/24/2017 - 17:47:16: [SM] Blaming: myjailbreak/warden.smx
L 11/24/2017 - 17:47:16: [SM] Call stack trace:
L 11/24/2017 - 17:47:16: [SM] [0] ConVar.BoolValue.get
L 11/24/2017 - 17:47:16: [SM] [1] Line 132, MyJailbreak/Modules/Warden/friendlyfire.sp::FriendlyFire_Event_RoundEnd
```
all other console messages are map or srcds related.

This error is mysterious. It says something like: can't read 'mp_friendlyfire' correctly.

Could you check your servers console when typing mp_friendlyfire, do you get a normal response or do you get `Unknown command "mp_friendlyfire"`

**Comment by damian1231** [comment]
No that is a valid command.

**Comment by shanapu** [comment]
please don't edit your previous post when I already answerd. make a new post...

**Comment by damian1231** [comment]
Im not sure why it didnt post the full log. However mp_friendlyfire 0/1 works fine

**Comment by shanapu** [comment]
```
L 11/24/2017 - 19:50:51: [SM] Exception reported: Fatal error creating dynamic native!
L 11/24/2017 - 19:50:51: [SM] Blaming: MyJailbreak/warden.smx
L 11/24/2017 - 19:50:51: [SM] Call stack trace:
L 11/24/2017 - 19:50:51: [SM] [0] CreateNative
L 11/24/2017 - 19:50:51: [SM] [1] Line 1358, MyJailbreak/warden.sp::AskPluginLoad2
L 11/24/2017 - 19:50:51: [SM] Failed to load plugin "MyJailbreak/warden.smx": **unexpected error 23 in AskPluginLoad callback.**
```
Also when we are here on css please check and read the faq for myJailbreak
https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#i-have-this-error


`[SM] Failed to load plugin "MyJailbreak\warden.smx": **unexpected error 23 in AskPluginLoad callback.**`
> Seems you have **two** warden **plugins installed**. Remove your old warden plugin and use only MyJailbreak Warden.

....you have two installation on myjb enabled on your server.

**Comment by damian1231** [comment]
ah i see mate its because of the capital letter folder still there
