### ISSUE TITLE
Arms Race

### ISSUE THREAD

**Issue by damian1231** [shanapu/MyJailbreak-CSS#3]
weapon list in Arms Race must still be csgo as after p90 goes to knife and user cant level up

**Comment by shanapu** [comment]
which one of these is not in css?  oO

weapon_p90
weapon_xm1014
weapon_galilar
weapon_famas
weapon_ak47
weapon_m4a1
weapon_sg556
weapon_aug
weapon_awp
weapon_m249
weapon_glock
weapon_hkp2000
weapon_p250
weapon_deagle
weapon_fiveseven
weapon_elite
weapon_knife

https://github.com/shanapu/MyJailbreak-CSS/blob/master/addons/sourcemod/configs/myjailbreak/armsrace.ini

**Comment by damian1231** [comment]
"cstrike"
	{
		"usp"
		{
			"name"		"USP"
			"type"		"secondary"
		}
		"glock"
		{
			"name"		"Glock"
			"type"		"secondary"
		}
		"deagle"
		{
			"name"		"Deagle"
			"type"		"secondary"
		}
		"p228"
		{
			"name"		"P228"
			"type"		"secondary"
		}
		"elite"
		{
			"name"		"Elite"
			"type"		"secondary"
		}
		"fiveseven"
		{
			"name"		"Five Seven"
			"type"		"secondary"
		}
		"m4a1"
		{
			"name"		"M4A1"
			"type"		"primary"
		}
		"ak47"
		{
			"name"		"AK47"
			"type"		"primary"
		}
		"aug"
		{
			"name"		"Steyr AUG"
			"type"		"primary"
		}
		"sg552"
		{
			"name"		"SG552"
			"type"		"primary"
		}
		"galil"
		{
			"name"		"Galil"
			"type"		"primary"
		}
		"famas"
		{
			"name"		"Famas"
			"type"		"primary"
		}
		"scout"
		{
			"name"		"Scout"
			"type"		"primary"
		}
		"sg550"
		{
			"name"		"SG550"
			"type"		"primary"
		}
		"m249"
		{
			"name"		"M249"
			"type"		"primary"
		}
		"g3sg1"
		{
			"name"		"G3SG1"
			"type"		"primary"
		}
		"ump45"
		{
			"name"		"UMP 45"
			"type"		"primary"
		}
		"mp5navy"
		{
			"name"		"MP5 Navy"
			"type"		"primary"
		}
		"m3"
		{
			"name"		"M3"
			"type"		"primary"
		}
		"xm1014"
		{
			"name"		"xm1014"
			"type"		"primary"
		}
		"tmp"
		{
			"name"		"TMP"
			"type"		"primary"
		}
		"mac10"
		{
			"name"		"Mac 10"
			"type"		"primary"
		}
		"p90"
		{
			"name"		"P90"
			"type"		"primary"
		}
		"awp"
		{
			"name"		"AWP"
			"type"		"primary"
		}
		"smokegrenade"
		{
			"name"		"Smode Grenade"
			"type"		"grenade"
		}
		"hegrenade"
		{
			"name"		"HE Grenade"
			"type"		"grenade"
		}
		"flashbang"
		{
			"name"		"Flashbang"
			"type"		"grenade"
		}
		"c4"
		{
			"name"		"C4"
			"type"		"c4"
		}

Credit to CSSDM

**Comment by shanapu** [comment]
This is useless. I need the weapon class name. 

But all the weapons in armsrace.ini are CSS weapons right?

**Comment by shanapu** [comment]
weapon_galil**ar** is called in css weapon_galil

fixed

**Comment by damian1231** [comment]
sg556 is csgo too bro
css is 552/550


these weapons too:
weapon_hkp2000
weapon_p250

**Comment by damian1231** [comment]
Some people on T do not respawn?
