### ISSUE TITLE
Damage Day

### ISSUE THREAD

**Issue by damian1231** [shanapu/MyJailbreak-CSS#8]
![ddd](https://user-images.githubusercontent.com/32046008/33230992-5b2a1358-d1e5-11e7-9416-79d7b7b76ef2.png)
DealDMG Day models are errors does nothing never ends after about 1.5mins it adds a beacon to players but does not do anything... when slaying players to change round it shows results, other than a slay there is no way to end that round, also the next round after its DDDay, after this one 1 player from T was able to spawn, i was not able to find a reason why as they are bots but even on a fresh round and a new gamemode(Drunken day) they were not respawned after the Deal DMG Day event. 

Edit: ScreenShot added

**Comment by shanapu** [comment]
I forgot to add the models for this.
And I fixed the HUD.
Everything else should worked as indeed. Round ended after given time and results are shown.
